import "./styles/Legal.css";
const EFFECTIVE_DATE = new Date(new Date().getFullYear(), 0, 1)
  .toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

const SECTIONS = [
  {
    title: "Acceptance of Terms",
    body: `By creating an account or using CortexWiki, you agree to these Terms of Service. If you do not agree, do not use the service. These terms apply to all users.`,
  },
  {
    title: "Use of the Service",
    body: `CortexWiki is a personal AI knowledge workspace. You may use it to ingest publicly accessible web content and YouTube videos, ask questions against your knowledge base, and explore knowledge graphs. You are responsible for ensuring that content you ingest does not violate third-party rights.`,
  },
  {
    title: "Prohibited Conduct",
    body: `You may not use CortexWiki to ingest or generate illegal content, attempt to reverse-engineer the service, circumvent authentication, abuse the API, or resell access. Accounts found in violation may be terminated without notice.`,
  },
  {
    title: "Intellectual Property",
    body: `CortexWiki and its underlying code, design, and models are the property of Snehanshu Sekhar Jena. Content you ingest remains your own. You grant CortexWiki a limited licence to process and store that content solely to provide the service.`,
  },
  {
    title: "AI-Generated Content",
    body: `Responses generated by CortexWiki are produced by AI models and may contain errors. They are grounded in your ingested sources, but you should verify important information before relying on it. CortexWiki is not liable for decisions made based on AI-generated responses.`,
  },
  {
    title: "Service Availability",
    body: `We aim for high availability but do not guarantee uninterrupted access. The service may be modified, suspended, or discontinued at any time. We are not liable for any loss arising from service interruptions.`,
  },
  {
    title: "Limitation of Liability",
    body: `CortexWiki is provided "as is" without warranties of any kind. To the maximum extent permitted by law, Snehanshu Sekhar Jena is not liable for indirect, incidental, or consequential damages arising from your use of the service.`,
  },
  {
    title: "Changes to Terms",
    body: `We may update these terms. The "Effective date" will be updated accordingly. Continued use after changes constitutes acceptance. For material changes, we will make reasonable efforts to notify registered users.`,
  },
  {
    title: "Contact",
    body: `Questions about these terms? Email snehanshusekhar99@gmail.com.`,
  },
];

function TermsOfService() {
  return (
    <main className="legal-page">
      <div className="legal-inner">
        <div className="legal-header">
          <span className="legal-eyebrow">Legal</span>
          <h1>Terms of Service</h1>
          <p className="legal-meta">Effective date: {EFFECTIVE_DATE}</p>
          <p className="legal-intro">
            These terms govern your use of CortexWiki. Please read them carefully.
            They're written to be clear, not to obscure your rights.
          </p>
        </div>

        <div className="legal-sections">
          {SECTIONS.map((s, i) => (
            <section key={i} className="legal-section">
              <h2>{s.title}</h2>
              <p>{s.body}</p>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}

export default TermsOfService;